"""End-to-end smoke tests for the sfx-plan CLI."""
from __future__ import annotations

import json
from pathlib import Path

from sfx_plan.cli import main


def test_cli_emits_sfx_html(video_dir: Path, catalog_path: Path, capsys) -> None:
    rc = main([
        str(video_dir),
        "--catalog", str(catalog_path),
    ])
    assert rc == 0
    sfx = video_dir / "compositions" / "sfx.html"
    assert sfx.exists()
    text = sfx.read_text(encoding="utf-8")
    assert "GENERATED by tools/sfx-plan" in text
    assert text.count("<audio\n") == 3


def test_cli_mounts_sfx_layer_in_index(video_dir: Path, catalog_path: Path) -> None:
    main([str(video_dir), "--catalog", str(catalog_path)])
    idx = (video_dir / "index.html").read_text(encoding="utf-8")
    assert 'data-composition-src="compositions/sfx.html"' in idx


def test_cli_dry_run_does_not_write(video_dir: Path, catalog_path: Path) -> None:
    main([str(video_dir), "--catalog", str(catalog_path), "--dry-run"])
    assert not (video_dir / "compositions" / "sfx.html").exists()


def test_cli_report_prints_plan_table(video_dir: Path, catalog_path: Path, capsys) -> None:
    main([str(video_dir), "--catalog", str(catalog_path), "--report"])
    captured = capsys.readouterr()
    assert "mode=" in captured.out
    assert "ui-tick" in captured.out


def test_cli_runs_overrides_loader_when_file_present(
    video_dir: Path, catalog_path: Path, capsys,
) -> None:
    (video_dir / "sfx-overrides.yml").write_text(
        "cues:\n  ui-tick:\n    default_volume: 0.5\n    filter:\n      brightness_in: ['bright']\n",
        encoding="utf-8",
    )
    rc = main([str(video_dir), "--catalog", str(catalog_path)])
    captured = capsys.readouterr()
    assert rc == 0
    assert "applied per-video overrides" in captured.out


def test_cli_passes_mount_offsets_to_at_scene_ms_annotations(
    video_dir: Path, catalog_path: Path,
) -> None:
    # Add a mount in index.html with a non-zero data-start...
    idx_path = video_dir / "index.html"
    idx_path.write_text(
        '<html><body>'
        '<div data-composition-id="main" data-start="0" data-duration="60" data-width="1920" data-height="1080">'
        '<audio id="vo" data-start="0" data-duration="60" data-track-index="9" src="audio/vo.mp3"></audio>'
        '<div id="sc1" data-composition-src="compositions/visual.html" data-start="5.0" data-duration="10"></div>'
        '</div></body></html>',
        encoding="utf-8",
    )
    # ...and an at-scene-ms annotation inside that composition.
    (video_dir / "compositions" / "visual.html").write_text(
        '<html><body><div id="v" data-sfx-on-anchor="ui-tick" data-sfx-at-scene-ms="1000"></div></body></html>',
        encoding="utf-8",
    )
    rc = main([str(video_dir), "--catalog", str(catalog_path), "--dry-run"])
    assert rc == 0
    # Plan should resolve to roughly 5.0 + 1.0 - peak_time_s(0.05) = 5.95s


def test_cli_default_run_is_per_cue_with_preload_none(video_dir: Path, catalog_path: Path) -> None:
    main([str(video_dir), "--catalog", str(catalog_path)])
    text = (video_dir / "compositions" / "sfx.html").read_text(encoding="utf-8")
    assert text.count("<audio\n") == 3
    assert 'preload="none"' in text
    assert not (video_dir / "compositions" / "sfx.cues.json").exists()


def test_cli_bake_emits_single_element_and_manifest(
    video_dir: Path, catalog_path: Path, monkeypatch,
) -> None:
    import sfx_plan.cli as cli_mod

    def _stub_bake(*, video_dir, out_rel, **_kwargs):
        out = video_dir / out_rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(b"\x00\x00")
        return out

    monkeypatch.setattr(cli_mod, "bake_sfx_mix", _stub_bake)
    rc = main([str(video_dir), "--catalog", str(catalog_path), "--bake"])
    assert rc == 0
    sfx = (video_dir / "compositions" / "sfx.html").read_text(encoding="utf-8")
    assert sfx.count("<audio") == 1
    assert 'id="sfx-mix"' in sfx
    assert 'preload="none"' not in sfx
    assert (video_dir / "audio" / "sfx-mix.mp3").exists()
    manifest = video_dir / "compositions" / "sfx.cues.json"
    assert manifest.exists()
    data = json.loads(manifest.read_text(encoding="utf-8"))
    assert len(data["cues"]) == 3


def test_cli_dry_run_does_not_bake(video_dir: Path, catalog_path: Path, monkeypatch) -> None:
    import sfx_plan.cli as cli_mod

    def _boom(**_kwargs):
        raise AssertionError("ffmpeg bake must not run under --dry-run")

    monkeypatch.setattr(cli_mod, "bake_sfx_mix", _boom)
    rc = main([str(video_dir), "--catalog", str(catalog_path), "--bake", "--dry-run"])
    assert rc == 0
    assert not (video_dir / "compositions" / "sfx.html").exists()


def test_cli_returns_nonzero_on_missing_timing_reference(video_dir: Path, catalog_path: Path, capsys) -> None:
    extra = video_dir / "compositions" / "broken.html"
    extra.write_text(
        '<html><body><div id="b" data-sfx-on-anchor="ui-tick"></div></body></html>',
        encoding="utf-8",
    )
    rc = main([str(video_dir), "--catalog", str(catalog_path)])
    assert rc != 0
    captured = capsys.readouterr()
    assert "data-sfx-at-scene-ms" in captured.err
