"""Tests for sfx.html emission, asset staging, and index.html mount wiring."""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from sfx_plan.plan import Cue
from sfx_plan.emit import (
    SFX_LAYER_ID,
    SFX_MIX_ID,
    ensure_mount,
    render_sfx_html,
    render_sfx_html_baked,
    stage_assets,
    write_cue_manifest,
)


def _cue(start: float = 1.0, cue: str = "ui-tick", src: str = "Mister Horse/Click/click-bright-01.wav",
         at_scene_ms: int = 1234) -> Cue:
    return Cue(
        data_start=start, duration_s=0.4, volume=0.8, pan=0.0,
        track_index=20, src=src, cue=cue,
        source="index.html:9", clamped=False, at_scene_ms=at_scene_ms,
    )


@pytest.fixture
def staged_video(tmp_path: Path) -> tuple[Path, Path, dict[str, str]]:
    """A scratch video folder + sound-effects root + staged-asset map."""
    video = tmp_path / "videos" / "demo"
    video.mkdir(parents=True)
    (video / "compositions").mkdir()
    sfx_root = tmp_path / "sound-effects"
    asset_path = sfx_root / "Mister Horse" / "Click" / "click-bright-01.wav"
    asset_path.parent.mkdir(parents=True)
    asset_path.write_bytes(b"\x00\x01\x02")
    cues = [_cue()]
    staged = stage_assets(cues, sound_effects_root=sfx_root, video_dir=video)
    return video, sfx_root, staged


def test_stage_assets_symlinks_into_video_folder(staged_video) -> None:
    video, _root, staged = staged_video
    assert staged["Mister Horse/Click/click-bright-01.wav"] == "assets/sfx/click-bright-01.wav"
    dest = video / "assets" / "sfx" / "click-bright-01.wav"
    assert dest.exists()
    assert dest.is_symlink()
    assert dest.read_bytes() == b"\x00\x01\x02"


def test_stage_assets_uses_relative_symlink_target(staged_video) -> None:
    video, _root, _staged = staged_video
    dest = video / "assets" / "sfx" / "click-bright-01.wav"
    target = os.readlink(dest)
    assert not os.path.isabs(target), f"symlink target must be relative for portability, got {target!r}"


def test_stage_assets_handles_name_collisions(tmp_path: Path) -> None:
    video = tmp_path / "v"; video.mkdir()
    sfx_root = tmp_path / "sfx"
    (sfx_root / "A" / "shared").mkdir(parents=True)
    (sfx_root / "B" / "shared").mkdir(parents=True)
    (sfx_root / "A" / "shared" / "x.wav").write_bytes(b"\x00")
    (sfx_root / "B" / "shared" / "x.wav").write_bytes(b"\x00\x01\x02")
    cues = [_cue(src="A/shared/x.wav"), _cue(src="B/shared/x.wav")]
    staged = stage_assets(cues, sound_effects_root=sfx_root, video_dir=video)
    assert staged["A/shared/x.wav"] != staged["B/shared/x.wav"]
    dest_a = video / staged["A/shared/x.wav"]
    dest_b = video / staged["B/shared/x.wav"]
    assert dest_a.exists() and dest_a.is_symlink()
    assert dest_b.exists() and dest_b.is_symlink()


def test_stage_assets_replaces_dangling_symlink(tmp_path: Path) -> None:
    video = tmp_path / "videos" / "demo"
    (video / "assets" / "sfx").mkdir(parents=True)
    sfx_root = tmp_path / "sound-effects"
    asset_path = sfx_root / "Mister Horse" / "Click" / "click-bright-01.wav"
    asset_path.parent.mkdir(parents=True)
    asset_path.write_bytes(b"\x00\x01\x02")
    dangling = video / "assets" / "sfx" / "click-bright-01.wav"
    dangling.symlink_to("../../../nonexistent/path.wav")
    assert dangling.is_symlink() and not dangling.exists()
    staged = stage_assets([_cue()], sound_effects_root=sfx_root, video_dir=video)
    dest = video / staged["Mister Horse/Click/click-bright-01.wav"]
    assert dest.is_symlink()
    assert dest.read_bytes() == b"\x00\x01\x02"


def test_render_includes_generated_header(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue()],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc123",
        total_duration_s=60.0,
    )
    assert "GENERATED by tools/sfx-plan" in text
    assert "do not edit" in text.lower()


def test_render_wraps_in_template_and_composition_root(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue()],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc",
        total_duration_s=60.0,
    )
    assert f'<template id="{SFX_LAYER_ID}-template">' in text
    assert f'data-composition-id="{SFX_LAYER_ID}"' in text
    assert 'data-width="1920"' in text
    assert 'data-height="1080"' in text


def test_render_registers_timeline(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue()],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc",
        total_duration_s=60.0,
    )
    assert "window.__timelines" in text
    assert f'window.__timelines["{SFX_LAYER_ID}"]' in text
    assert "gsap.timeline" in text


def test_render_emits_audio_with_id_clip_and_staged_src(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue()],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc",
        total_duration_s=60.0,
    )
    assert 'id="sfx-001-ui-tick-scene-ms-1234"' in text
    assert 'class="clip"' in text
    # preload="none" defers per-cue media loading in the preview player; without it
    # the many SFX <audio> elements exhaust Chrome's WebMediaPlayer budget and freeze
    # preview Play. The compiler strips it for renders, so the mux is unaffected.
    assert 'preload="none"' in text
    assert 'src="../assets/sfx/click-bright-01.wav"' in text
    assert 'data-start="1.0"' in text
    assert 'data-duration="0.4"' in text
    assert 'data-volume="0.8"' in text
    assert 'data-track-index="20"' in text


def test_render_includes_source_comment_per_cue(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue()],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc",
        total_duration_s=60.0,
    )
    assert "from index.html:9" in text
    assert "at-scene-ms=1234" in text
    assert "cue=ui-tick" in text


def test_render_sorts_by_data_start(staged_video) -> None:
    video, _root, staged = staged_video
    text = render_sfx_html(
        cues=[_cue(start=5.0), _cue(start=1.0), _cue(start=3.0)],
        sfx_html_path=video / "compositions" / "sfx.html",
        video_dir=video,
        staged=staged,
        catalog_sha="abc",
        total_duration_s=60.0,
    )
    starts = [line for line in text.splitlines() if 'data-start="' in line and "audio" not in line]
    # extract data-start values in order of appearance
    extracted = []
    for line in text.splitlines():
        if 'data-start="' in line and 'audio' not in line:
            continue
    # Simpler: find all data-start occurrences in audio blocks
    import re
    starts_in_audio = [float(m) for m in re.findall(r'data-start="([0-9.]+)"', text)]
    assert starts_in_audio == sorted(starts_in_audio)


def test_ensure_mount_inserts_when_missing(tmp_path: Path) -> None:
    idx = tmp_path / "index.html"
    idx.write_text(
        '<html>\n<body>\n  <div id="root"></div>\n</body>\n</html>\n',
        encoding="utf-8",
    )
    inserted = ensure_mount(idx, total_duration_s=60.0)
    text = idx.read_text(encoding="utf-8")
    assert inserted is True
    assert 'data-composition-src="compositions/sfx.html"' in text
    assert 'data-start="0"' in text
    assert 'data-duration="60.0"' in text


def test_ensure_mount_is_idempotent(tmp_path: Path) -> None:
    idx = tmp_path / "index.html"
    idx.write_text(
        '<html>\n<body>\n  <div data-composition-src="compositions/sfx.html"></div>\n</body>\n</html>\n',
        encoding="utf-8",
    )
    inserted = ensure_mount(idx, total_duration_s=60.0)
    text = idx.read_text(encoding="utf-8")
    assert inserted is False
    assert text.count("compositions/sfx.html") == 1


def test_ensure_mount_refreshes_short_duration(tmp_path: Path) -> None:
    """An existing mount whose data-duration is shorter than the full runtime
    (the old last-cue-end behavior) gets refreshed so late cues aren't clipped."""
    idx = tmp_path / "index.html"
    idx.write_text(
        '<html>\n<body>\n  <div\n'
        '    id="sfx-layer"\n'
        '    data-composition-src="compositions/sfx.html"\n'
        '    data-start="0"\n'
        '    data-duration="11.2"\n'
        '    data-track-index="19"\n'
        '  ></div>\n</body>\n</html>\n',
        encoding="utf-8",
    )
    changed = ensure_mount(idx, total_duration_s=120.001)
    text = idx.read_text(encoding="utf-8")
    assert changed is True
    assert text.count("compositions/sfx.html") == 1
    assert 'data-duration="11.2"' not in text
    assert 'data-duration="120.001"' in text
    # Re-running with the same duration is a no-op.
    assert ensure_mount(idx, total_duration_s=120.001) is False


def test_render_baked_emits_single_audio_element() -> None:
    text = render_sfx_html_baked(
        mix_rel="../audio/sfx-mix.mp3",
        total_duration_s=530.6,
        catalog_sha="abc123",
        cue_count=162,
    )
    # Exactly one <audio>, backed by the baked mix.
    assert text.count("<audio") == 1
    assert f'id="{SFX_MIX_ID}"' in text
    assert 'src="../audio/sfx-mix.mp3"' in text
    assert 'data-volume="1"' in text  # per-cue gains baked in
    assert 'data-duration="530.6"' in text
    assert 'data-track-index="19"' in text
    # A single player never overruns the budget, so no preload deferral.
    assert 'preload="none"' not in text
    # Scaffold intact (template + composition root + paused timeline).
    assert f'<template id="{SFX_LAYER_ID}-template">' in text
    assert f'data-composition-id="{SFX_LAYER_ID}"' in text
    assert "window.__timelines" in text


def test_write_cue_manifest_shape_and_ids(staged_video) -> None:
    video, _root, _staged = staged_video
    cues = [_cue(start=5.0), _cue(start=1.0, cue="boom"), _cue(start=3.0)]
    manifest_path = video / "compositions" / "sfx.cues.json"
    write_cue_manifest(cues=cues, path=manifest_path, total_duration_s=60.0)
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert data["version"] == 1
    assert data["total_duration_s"] == 60.0
    starts = [c["data_start"] for c in data["cues"]]
    assert starts == sorted(starts)
    # Ids are 1-based in data-start order, matching the per-cue sfx.html.
    assert data["cues"][0]["id"].startswith("sfx-001-")
    assert data["cues"][1]["id"].startswith("sfx-002-")
    first = data["cues"][0]
    for key in ("id", "data_start", "duration_s", "volume", "pan", "src", "cue", "at_scene_ms"):
        assert key in first
