[workspace]
resolver = "2"
members = ["crates/katto-engine", "crates/katto-cli", "src-tauri"]

[workspace.package]
version = "0.3.0"
edition = "2024"
authors = ["Akwasi Konadu Akuoko"]
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
