"""Emit compositions/sfx.html + stage assets into the video folder.

HyperFrames sub-compositions must (a) live inside the video folder for asset
discovery, (b) wrap content in a `<template>` + composition-root `<div>`,
(c) register the timeline on `window.__timelines`, and (d) tag every timed
media element with `class="clip"` and a stable `id`.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from sfx_plan.plan import Cue


SFX_LAYER_ID = "sfx-layer"
SFX_MOUNT_TRACK_INDEX = 19
SFX_MIX_ID = "sfx-mix"
SFX_MIX_REL = "../audio/sfx-mix.mp3"
CUE_MANIFEST_NAME = "sfx.cues.json"
_MOUNT_SRC = 'data-composition-src="compositions/sfx.html"'
# Match the sfx-layer mount's data-duration (it follows the src within the same tag).
_MOUNT_DURATION_RE = re.compile(
    r"(" + re.escape(_MOUNT_SRC) + r'[^>]*?data-duration=")([^"]*)(")',
    re.DOTALL,
)


def _slug(text: str) -> str:
    """ASCII-safe lowercase slug for use in HTML ids."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "x"


def _fmt_duration(seconds: float) -> str:
    """Format a duration for the mount's data-duration (raw float repr, as before)."""
    return f"{seconds}"


def stage_assets(
    cues: list[Cue],
    *,
    sound_effects_root: Path,
    video_dir: Path,
) -> dict[str, str]:
    """Stage each unique cue source as a relative symlink under `video_dir/assets/sfx/`.

    Returns a map from original `cue.src` (catalog-relative) to staged path
    (video-folder-relative). Files with name collisions get an 8-char hash prefix.
    Links are relative so the video folder stays portable across clones as long
    as `sound-effects/` lives at the repo root.
    """
    sfx_dir = video_dir / "assets" / "sfx"
    sfx_dir.mkdir(parents=True, exist_ok=True)
    staged: dict[str, str] = {}
    for cue in cues:
        if cue.src in staged:
            continue
        source = (sound_effects_root / cue.src).resolve()
        basename = source.name
        dest = sfx_dir / basename
        if dest.exists() and dest.stat().st_size != source.stat().st_size:
            h = hashlib.sha256(cue.src.encode("utf-8")).hexdigest()[:8]
            dest = sfx_dir / f"{h}-{basename}"
        if dest.is_symlink() and not dest.exists():
            dest.unlink()
        if not dest.exists():
            rel_target = os.path.relpath(source, start=dest.parent)
            dest.symlink_to(rel_target)
        staged[cue.src] = dest.relative_to(video_dir).as_posix()
    return staged


def _cue_id(cue: Cue, index: int) -> str:
    """Stable per-cue HTML id, shared by the per-cue tags and the bake manifest.

    `index` is the cue's 1-based position in data-start order, so ids match
    between `sfx.html` (per-cue mode) and `sfx.cues.json` (baked mode).
    """
    return f"sfx-{index:03d}-{cue.cue}-{_slug(f'scene-ms-{cue.at_scene_ms}')}"


def _audio_tag(*, cue: Cue, index: int, staged_rel: str, video_to_sfx_relpath: str) -> str:
    audio_id = _cue_id(cue, index)
    ref = f'at-scene-ms={cue.at_scene_ms}'
    comment = (
        f'        <!-- from {cue.source}  {ref}  '
        f'cue={cue.cue} -->'
    )
    pan = "" if cue.pan == 0.0 else f'\n          data-pan="{cue.pan}"'
    return (
        f'{comment}\n'
        f'        <audio\n'
        f'          id="{audio_id}"\n'
        f'          class="clip"\n'
        # preload="none" so the preview player loads each SFX only as its cue
        # nears, instead of instantiating a media player per element up front.
        # Without it the many SFX <audio> elements exhaust Chrome's
        # WebMediaPlayer budget and freeze preview Play (scrub still works).
        # The compiler strips preload for renders, so the offline mux is
        # unaffected. See memory: hyperframes-preview-audio-element-overload.
        f'          preload="none"\n'
        f'          data-start="{cue.data_start}"\n'
        f'          data-duration="{cue.duration_s}"\n'
        f'          data-volume="{cue.volume}"{pan}\n'
        f'          data-track-index="{cue.track_index}"\n'
        f'          src="{video_to_sfx_relpath}/{Path(staged_rel).name}"\n'
        f'        ></audio>'
    )


def _sfx_document(*, audio_blocks: str, cue_count: int, total_duration_s: float, catalog_sha: str) -> str:
    """Wrap the audio block(s) in the shared HyperFrames sub-composition scaffold.

    Both the per-cue renderer (`render_sfx_html`) and the baked renderer
    (`render_sfx_html_baked`) emit the same template + composition-root div +
    paused-timeline IIFE; only `audio_blocks` differs.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!--\n"
        f"  GENERATED by tools/sfx-plan — do not edit by hand.\n"
        f"  Source: sfx-plan v1, run at {ts}\n"
        f"  Cues: {cue_count}   Duration: {total_duration_s:.1f}s   "
        f"Catalog: sfx-catalog.yml@{catalog_sha[:12]}\n"
        f"-->\n"
        f'<!doctype html>\n'
        f'<html lang="en">\n'
        f'  <head>\n'
        f'    <meta charset="UTF-8" />\n'
        f'    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>\n'
        f'  </head>\n'
        f'  <body>\n'
        f'    <template id="{SFX_LAYER_ID}-template">\n'
        f'      <div\n'
        f'        data-composition-id="{SFX_LAYER_ID}"\n'
        f'        data-width="1920"\n'
        f'        data-height="1080"\n'
        f'      >\n'
        f'{audio_blocks}\n'
        f'        <script>\n'
        f'          (() => {{\n'
        f'            window.__timelines = window.__timelines || {{}};\n'
        f'            window.__timelines["{SFX_LAYER_ID}"] = gsap.timeline({{ paused: true }});\n'
        f'          }})();\n'
        f'        </script>\n'
        f'      </div>\n'
        f'    </template>\n'
        f'  </body>\n'
        f'</html>\n'
    )


def render_sfx_html(
    *,
    cues: list[Cue],
    sfx_html_path: Path,
    video_dir: Path,
    staged: dict[str, str],
    catalog_sha: str,
    total_duration_s: float,
) -> str:
    """Per-cue (editing-default) sfx.html: one `<audio preload="none">` per cue."""
    ordered = sorted(cues, key=lambda c: c.data_start)
    # Compute relative path from sfx.html's parent to assets/sfx (typically "../assets/sfx").
    sfx_assets_dir = (video_dir / "assets" / "sfx").resolve()
    sfx_html_parent = sfx_html_path.parent.resolve()
    rel_to_sfx = os.path.relpath(sfx_assets_dir, start=sfx_html_parent).replace(os.sep, "/")

    audio_blocks = "\n".join(
        _audio_tag(
            cue=c,
            index=i + 1,
            staged_rel=staged[c.src],
            video_to_sfx_relpath=rel_to_sfx,
        )
        for i, c in enumerate(ordered)
    )

    return _sfx_document(
        audio_blocks=audio_blocks,
        cue_count=len(ordered),
        total_duration_s=total_duration_s,
        catalog_sha=catalog_sha,
    )


def render_sfx_html_baked(
    *,
    mix_rel: str,
    total_duration_s: float,
    catalog_sha: str,
    cue_count: int,
) -> str:
    """Baked (finalize) sfx.html: ONE `<audio>` backed by the pre-mixed track.

    Every cue's fixed 0.4 peg (`plan.PEG_VOLUME`) is already baked into the mix,
    so the single mounted layer plays at unity — `data-volume="1"`. No
    `preload="none"` — a single media element never overruns the player budget,
    and deferring it would only delay the SFX. Mirrors the music.html single-bed
    shape used elsewhere in the project.
    """
    audio_block = (
        f'        <!-- baked SFX mix: {cue_count} cues, generated by tools/sfx-plan --bake -->\n'
        f'        <audio\n'
        f'          id="{SFX_MIX_ID}"\n'
        f'          class="clip"\n'
        f'          data-start="0"\n'
        f'          data-duration="{total_duration_s}"\n'
        f'          data-volume="1"\n'
        f'          data-track-index="{SFX_MOUNT_TRACK_INDEX}"\n'
        f'          src="{mix_rel}"\n'
        f'        ></audio>'
    )
    return _sfx_document(
        audio_blocks=audio_block,
        cue_count=cue_count,
        total_duration_s=total_duration_s,
        catalog_sha=catalog_sha,
    )


def write_cue_manifest(*, cues: list[Cue], path: Path, total_duration_s: float) -> None:
    """Write compositions/sfx.cues.json so tooling can recover per-cue timing.

    The baked sfx.html holds one element, so `sfx-level --batch` (and any other
    per-cue consumer) reads this manifest instead. Cue ids match the per-cue
    `sfx.html` exactly (shared `_cue_id`).
    """
    ordered = sorted(cues, key=lambda c: c.data_start)
    manifest = {
        "version": 1,
        "total_duration_s": total_duration_s,
        "cues": [
            {
                "id": _cue_id(c, i + 1),
                "data_start": c.data_start,
                "duration_s": c.duration_s,
                "volume": c.volume,
                "pan": c.pan,
                "src": c.src,
                "cue": c.cue,
                "at_scene_ms": c.at_scene_ms,
            }
            for i, c in enumerate(ordered)
        ],
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def _mount_block(total_duration_s: float) -> str:
    return (
        '      <!-- sfx-layer: generated by tools/sfx-plan, do not edit -->\n'
        '      <div\n'
        f'        id="{SFX_LAYER_ID}"\n'
        f'        data-composition-id="{SFX_LAYER_ID}"\n'
        f'        data-composition-src="compositions/sfx.html"\n'
        f'        data-start="0"\n'
        f'        data-duration="{_fmt_duration(total_duration_s)}"\n'
        f'        data-track-index="{SFX_MOUNT_TRACK_INDEX}"\n'
        '      ></div>\n'
    )


def ensure_mount(index_html_path: Path, *, total_duration_s: float) -> bool:
    """Upsert the sfx-layer mount in index.html. Returns True if changed.

    If the mount is absent, insert it. If it already exists, refresh its
    `data-duration` to `total_duration_s` — the mount must span the full runtime
    or HyperFrames silently clips every cue scheduled past its end.
    """
    text = index_html_path.read_text(encoding="utf-8")
    duration = _fmt_duration(total_duration_s)
    if _MOUNT_SRC in text:
        new_text, n = _MOUNT_DURATION_RE.subn(rf"\g<1>{duration}\g<3>", text, count=1)
        if n and new_text != text:
            index_html_path.write_text(new_text, encoding="utf-8")
            return True
        return False
    mount = _mount_block(total_duration_s)
    if "</body>" in text:
        new_text = text.replace("</body>", mount + "</body>", 1)
    else:
        new_text = text + "\n" + mount
    index_html_path.write_text(new_text, encoding="utf-8")
    return True
