#!/usr/bin/env python3
"""Render thumbnailInspo/README.md from the catalog JSON the cataloging pass writes.

The cataloging agents do the judgment (vision-read each thumbnail, author its
layout/archetype/why-it-works) and drop one entry dict per thumbnail into
``tools/thumbnail-inspo/catalog/<slug>-<lo>.json`` (a JSON list). This renderer
is the mechanical half: it merges every catalog file, orders entries by channel
then rank, and writes the two-tier index (Quick-index table + Entries blocks).
Deterministic and idempotent — re-run any time the catalog changes.

Usage:
    python3 tools/thumbnail-inspo/build_readme.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG_DIR = Path(__file__).resolve().parent / "catalog"
README = ROOT / "thumbnailInspo" / "README.md"

HEADER = """# thumbnailInspo — the thumbnail reference index

The canonical thumbnail-composition reference for this project's videos. Every
entry is a real, high-performing thumbnail harvested from a proven creator, plus
a written **Layout map** precise enough to *rebuild the composition* with our own
content. The `thumbnail-and-title-generator` skill picks a reference here for
every thumbnail it makes — it does not design from a blank canvas. The contract
(pick -> grid -> replicate, plus how the library is grown) lives in `CLAUDE.md`.

Thumbnails are harvested by `tools/thumbnail-inspo/fetch.py` (top-N by views from
each channel's Popular playlist, or newest from the `/shorts` tab) into
`<channel-slug>/` folders with a per-channel `_manifest.json`. To read a
reference's exact element positions, grid it:

```bash
python3 tools/thumbnail-inspo/grid.py thumbnailInspo/<channel>/<file>.jpg
```

## How this index is read (two tiers)

1. **Scan the `## Quick index` table first** — one compact row per entry. Match
   the video's beat/emotion to a row from text alone.
2. **Drill into the matching `## Entries` block**, open *only* that entry's image
   (grid it if you need the positions), and replicate the `Layout map` with our
   content. Picking a reference is mandatory for every thumbnail.

This file is generated by `tools/thumbnail-inspo/build_readme.py` from the
cataloging pass — edit the catalog JSON (or re-catalog) and re-run, don't
hand-edit below this line.
"""


def as_list(v) -> list[str]:
    if v is None:
        return []
    if isinstance(v, list):
        return [str(x) for x in v]
    return [s.strip() for s in str(v).split(",") if s.strip()]


def face_str(v) -> str:
    if isinstance(v, bool):
        return "yes" if v else "no"
    return str(v or "").strip().lower() or "?"


def load_entries() -> list[dict]:
    entries: list[dict] = []
    if not CATALOG_DIR.exists():
        return entries
    for fp in sorted(CATALOG_DIR.glob("*.json")):
        try:
            data = json.loads(fp.read_text())
        except json.JSONDecodeError as exc:
            print(f"warning: {fp.name} unparseable: {exc}", file=sys.stderr)
            continue
        if isinstance(data, dict):
            data = data.get("entries", [])
        for e in data:
            if isinstance(e, dict) and e.get("slug"):
                entries.append(e)
    # order by channel then rank (rank parsed from the NN- filename prefix)
    def rank_of(e: dict) -> int:
        f = str(e.get("file", ""))
        head = f.split("-", 1)[0]
        return int(head) if head.isdigit() else 999
    entries.sort(key=lambda e: (str(e.get("channel", "")), rank_of(e)))
    # de-dup by slug (last write wins, but keep stable order)
    seen: dict[str, dict] = {}
    for e in entries:
        seen[e["slug"]] = e
    return list(seen.values())


def render(entries: list[dict]) -> str:
    out = [HEADER, "\n## Quick index\n"]
    out.append("| slug | channel | archetype | layout | device | face | accent | title_shape | use-when |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for e in entries:
        slug = e["slug"]
        dev = ", ".join(as_list(e.get("device")))
        out.append(
            f"| [{slug}](#{slug}) | {e.get('channel','')} | {e.get('archetype','')} "
            f"| {e.get('layout','')} | {dev} | {face_str(e.get('face'))} "
            f"| {e.get('accent','')} | {e.get('title_shape','')} "
            f"| {e.get('mimic_for', e.get('use_when','')).replace(chr(10),' ')} |"
        )

    out.append("\n## Entries\n")
    for e in entries:
        slug = e["slug"]
        dev = ", ".join(as_list(e.get("device")))
        img = f"{e.get('channel','')}/{e.get('file','')}"
        out.append(f"### {slug}")
        out.append(f"- Image: `{img}` · Source: {e.get('watch_url','')}")
        out.append(
            f"- Tags: archetype={e.get('archetype','')} · layout={e.get('layout','')} "
            f"· device=[{dev}] · face={face_str(e.get('face'))} "
            f"· accent={e.get('accent','')} · text={e.get('text','')}"
        )
        out.append(f"- Reads as: {e.get('reads_as','')}")
        out.append(f"- Layout map: {e.get('layout_map','')}")
        out.append(f"- Why it works: {e.get('why_it_works','')}")
        out.append(f"- Mimic for: {e.get('mimic_for','')}")
        if e.get("title"):
            out.append(
                f"- Original pair (shape to mimic, not copy): \"{e.get('title','')}\" "
                f"· title_shape={e.get('title_shape','')} · title_pattern={e.get('title_pattern','')}"
            )
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    entries = load_entries()
    if not entries:
        print("error: no catalog entries found in "
              f"{CATALOG_DIR}", file=sys.stderr)
        return 1
    README.write_text(render(entries))
    print(f"wrote {README} with {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
