// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, Error>(__TAURI_INVOKE("get_settings")),
	setSettings: (patch: SettingsPatch) => typedError<Settings, Error>(__TAURI_INVOKE("set_settings", { patch })),
	/**
	 *  Current studio-root reachability snapshot; broadcasts keep it fresh after
	 *  this initial query.
	 */
	getDriveStatus: () => typedError<DriveStatus, Error>(__TAURI_INVOKE("get_drive_status")),
	/**  Most-recent-first page of activity-log events. `before_id` pages backward. */
	listEvents: (limit: number, beforeId: number | null) => typedError<Event[], Error>(__TAURI_INVOKE("list_events", { limit, beforeId })),
	/**  List jobs newest-first. When `active_only`, restrict to `queued`/`running`. */
	listJobs: (activeOnly: boolean) => typedError<Job[], Error>(__TAURI_INVOKE("list_jobs", { activeOnly })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>i) } : v) as typeof v)),
	/**
	 *  Stream a job's progress over an IPC channel. Sends the current snapshot
	 *  first (a reopened WebView subscribes late), then live ticks until the job
	 *  reaches a terminal state.
	 */
	subscribeJobProgress: (jobId: string, onProgress: Channel<JobProgress>) => typedError<null, Error>(__TAURI_INVOKE("subscribe_job_progress", { jobId, onProgress })),
	/**
	 *  Dev helper: a 5-second synthetic job exercising the full pipeline
	 *  (progress stream, tray mirror, terminal events row). `fail` makes it die
	 *  halfway to exercise the failure path.
	 */
	devRunSmokeJob: (fail: boolean) => typedError<Job, Error>(__TAURI_INVOKE("dev_run_smoke_job", { fail })),
	/**
	 *  Open the native folder picker and inspect the chosen directory. `None` when
	 *  the user cancels. Nothing is persisted here — the wizard saves the path via
	 *  `set_settings` when the step is confirmed.
	 */
	pickStudioRoot: () => typedError<{
	path: string,
	writable: boolean,
	on_boot_volume: boolean,
	/**  Whole gigabytes free, `None` if the filesystem query failed. */
	free_gb: number | null,
	low_free_space: boolean,
} | null, Error>(__TAURI_INVOKE("pick_studio_root")),
	/**
	 *  Store a credential in the macOS keychain. The value is write-only: never
	 *  echoed back, never logged. Presence is recorded in the activity log by
	 *  service name only.
	 */
	storeKey: (service: KeyService, value: string) => typedError<null, Error>(__TAURI_INVOKE("store_key", { service, value })),
	/**  Whether a credential exists for `service`, without exposing its value. */
	keyPresent: (service: KeyService) => typedError<boolean, Error>(__TAURI_INVOKE("key_present", { service })),
	/**
	 *  `which claude` through a login shell, so the owner's PATH additions apply.
	 *  A found path is cached in settings for later phases; not-found is a normal
	 *  outcome, not an error.
	 */
	detectClaude: () => typedError<string | null, Error>(__TAURI_INVOKE("detect_claude")),
	/**
	 *  Finish the wizard: a saved studio root is the one hard requirement; keys
	 *  stay optional (Phase 1 runs no AI).
	 */
	completeOnboarding: () => typedError<null, Error>(__TAURI_INVOKE("complete_onboarding")),
	/**
	 *  Reconcile the projects index against the studio-root folders on demand
	 *  (folders are truth). Reads the configured `studio_root`, refuses when it is
	 *  unmounted, then scans `<root>/Projects`, diffs against the index, and applies.
	 * 
	 *  Returns an empty report when no studio root is configured yet.
	 */
	rescanProjects: () => typedError<ReconcileReport, Error>(__TAURI_INVOKE("rescan_projects")),
	/**  Every project row, most-recently-touched first. */
	listProjects: () => typedError<Project[], Error>(__TAURI_INVOKE("list_projects")),
	/**
	 *  One project with its manifest-validity flag and per-subfolder freshness.
	 *  Guards the studio-root mount before reading any folder.
	 */
	getProject: (slug: string) => typedError<ProjectDetail, Error>(__TAURI_INVOKE("get_project", { slug })),
	/**
	 *  Create a new project: dedupe the slug against the index, lay down the D6
	 *  folder skeleton with a fresh `project.json`, insert and touch the row, record
	 *  a `project-created` event, and broadcast. All folder + DB work runs on the
	 *  single writer thread so the slug dedupe and the folder creation cannot race.
	 */
	createProject: (title: string, shootDate: string | null) => typedError<Project, Error>(__TAURI_INVOKE("create_project", { title, shootDate })),
	/**
	 *  Move a project through the status vocabulary. Writes both the manifest
	 *  (atomic) and the row — folders are truth — then touches the row, records an
	 *  event, and broadcasts.
	 */
	setProjectStatus: (slug: string, status: string) => typedError<null, Error>(__TAURI_INVOKE("set_project_status", { slug, status })),
	/**
	 *  Set (or clear) a project's shoot and publish dates. Writes the manifest
	 *  (atomic) and the row, touches, records an event, and broadcasts.
	 */
	setProjectDates: (slug: string, shoot: string | null, publish: string | null) => typedError<null, Error>(__TAURI_INVOKE("set_project_dates", { slug, shoot, publish })),
	/**
	 *  Reveal a project folder (or one of its D6 subfolders) in Finder. `subfolder`
	 *  is validated against the anatomy allowlist so it can never escape the project
	 *  directory.
	 */
	revealProjectFolder: (slug: string, subfolder: string | null) => typedError<null, Error>(__TAURI_INVOKE("reveal_project_folder", { slug, subfolder })),
	/**  Ideas with the given status, newest-first. */
	listIdeas: (status: string) => typedError<Idea[], Error>(__TAURI_INVOKE("list_ideas", { status })),
	/**  Capture a new idea into the backlog and broadcast. */
	createIdea: (input: IdeaCreate) => typedError<Idea, Error>(__TAURI_INVOKE("create_idea", { input })),
	/**  Patch an idea's editable fields and return the updated row. */
	updateIdea: (id: string, patch: IdeaPatch) => typedError<Idea, Error>(__TAURI_INVOKE("update_idea", { id, patch })),
	/**
	 *  Discard an idea: it moves to `status='discarded'` and the row is retained as
	 *  an audit trail (never deleted).
	 */
	discardIdea: (id: string) => typedError<null, Error>(__TAURI_INVOKE("discard_idea", { id })),
	/**
	 *  Promote a backlog idea into a real project folder in one motion. All the DB
	 *  work runs inside a single rusqlite transaction on the writer thread; the
	 *  folder skeleton is filesystem state the transaction cannot cover, so a
	 *  DB-side failure rolls the rows back and then explicitly removes the folder.
	 *  On success the idea stays as a `promoted` audit row pointing at the new slug.
	 */
	promoteIdea: (id: string) => typedError<PromoteResult, Error>(__TAURI_INVOKE("promote_idea", { id })),
	/**
	 *  Land a quick-capture idea into the backlog and broadcast. Same defaults as
	 *  [`create_idea`] (`type='manual'`, `status='backlog'`), reshaped for the capture
	 *  window's flat `title`/`note`/`kind` fields. The capture window closes itself on
	 *  the frontend once this resolves.
	 */
	captureSubmit: (title: string, note: string | null, kind: string | null) => typedError<null, Error>(__TAURI_INVOKE("capture_submit", { title, note, kind })),
	/**
	 *  Schedule entries whose date falls within `[from, to]` (inclusive ISO bounds),
	 *  ordered by date. Drives the calendar's month/week views.
	 */
	listSchedule: (from: string, to: string) => typedError<ScheduleEntry[], Error>(__TAURI_INVOKE("list_schedule", { from, to })),
	/**
	 *  Pin a project to a date. There is at most one entry per `(project_slug, kind)`
	 *  pair, so this inserts or updates in place. Broadcasts `schedule-changed`, which
	 *  also refreshes the tray's next-shoot line.
	 */
	upsertScheduleEntry: (projectSlug: string, kind: string, date: string, note: string | null) => typedError<ScheduleEntry, Error>(__TAURI_INVOKE("upsert_schedule_entry", { projectSlug, kind, date, note })),
	/**  Remove a schedule entry by id and broadcast `schedule-changed`. */
	deleteScheduleEntry: (id: RowId) => typedError<null, Error>(__TAURI_INVOKE("delete_schedule_entry", { id })),
	/**
	 *  Enable or disable launch-at-login, recording the change in the activity
	 *  log. The AppleScript-backed call can block, so it runs off the runtime.
	 */
	setAutostart: (enabled: boolean) => typedError<null, Error>(__TAURI_INVOKE("set_autostart", { enabled })),
	/**  Whether launch-at-login is currently enabled at the OS level. */
	getAutostart: () => typedError<boolean, Error>(__TAURI_INVOKE("get_autostart")),
	/**
	 *  Close the main window: the WebView is destroyed and katto stays resident
	 *  in the tray (same path as clicking the window's close button).
	 */
	sleepToTray: () => typedError<null, Error>(__TAURI_INVOKE("sleep_to_tray")),
	/**  Exit katto completely (same exit path as the tray's Quit item). */
	quitApp: () => typedError<null, Error>(__TAURI_INVOKE("quit_app")),
};

/** Events */
export const events = {
	deepLinkOpened: makeEvent<DeepLinkOpened>("deep-link-opened"),
	driveStatusChanged: makeEvent<DriveStatusChanged>("drive-status-changed"),
	eventsAppended: makeEvent<EventsAppended>("events-appended"),
	ideasChanged: makeEvent<IdeasChanged>("ideas-changed"),
	jobsChanged: makeEvent<JobsChanged>("jobs-changed"),
	projectsChanged: makeEvent<ProjectsChanged>("projects-changed"),
	scheduleChanged: makeEvent<ScheduleChanged>("schedule-changed"),
};

/* Types */
/**
 *  Broadcast when a `katto://` deep link is opened (notification click or OS
 *  LaunchServices open); the frontend router navigates to `route` (`"ideas"` or
 *  `"project/<slug>"`).
 */
export type DeepLinkOpened = {
	route: string,
};

/**
 *  Snapshot of the studio root's reachability. `path: None` means no root is
 *  configured yet (pre-onboarding) — reported as mounted so no banner shows.
 */
export type DriveStatus = {
	mounted: boolean,
	path: string | null,
	free_gb: number | null,
};

/**  Broadcast on studio-root mount transitions (and once at watcher start). */
export type DriveStatusChanged = {
	mounted: boolean,
	path: string,
};

/**
 *  The application error type crossing every command boundary.
 * 
 *  Each variant carries a pre-formatted message string, and serde derives the
 *  tagged `{ kind, message }` wire shape (`kind` = snake_case variant name). The
 *  frontend switches on the stable `kind` slug. `specta::Type` (added alongside
 *  the command layer) types the same shape for the generated bindings, keeping
 *  Rust and TypeScript in lockstep without a hand-written impl.
 */
export type Error = { kind: "db"; message: string } | { kind: "migration"; message: string } | { kind: "job_transition"; message: string } | { kind: "io"; message: string } | { kind: "db_closed"; message: string } | { kind: "keychain"; message: string } | { kind: "onboarding"; message: string } | { kind: "autostart"; message: string } | { kind: "studio_root_unmounted"; message: string } | { kind: "invalid_manifest"; message: string } | { kind: "promote_failed"; message: string };

/**  A row in the append-only activity log. */
export type Event = {
	id: RowId,
	ts: string,
	kind: string,
	project_slug: string | null,
	payload_json: string | null,
};

/**  Broadcast after any `events` row is written; the dashboard refetches its feed. */
export type EventsAppended = null;

/**
 *  Per-subfolder freshness for a project's D6 anatomy: how many files a subfolder
 *  holds (non-recursive) and the newest file mtime. `latest_mtime` is `None` for
 *  an empty or absent subfolder. Feeds the project-detail "what has activity"
 *  grid — never a score, only a raw count and timestamp.
 */
export type FolderFreshness = {
	subfolder: string,
	file_count: number,
	latest_mtime: string | null,
};

/**
 *  An idea row. Column parity with hyper-frames `tools/studio` (D7: no numeric
 *  score or ranking fields). `status` moves `backlog -> promoted | discarded`;
 *  discarded rows are kept as an audit trail rather than deleted.
 */
export type Idea = {
	id: string,
	type: string,
	kind: string,
	status: string,
	title: string,
	rationale: string | null,
	source: string | null,
	source_url: string | null,
	source_title: string | null,
	evidence_json: string | null,
	raw_signal_id: string | null,
	first_seen: string,
	notes: string | null,
	promoted_slug: string | null,
	kind_source: string | null,
	kind_why: string | null,
};

/**
 *  Fields for a manually captured idea. Everything else is defaulted server-side
 *  (`type='manual'`, `status='backlog'`, a fresh id, and the capture timestamp).
 */
export type IdeaCreate = {
	title: string,
	kind: string | null,
	notes: string | null,
};

/**  A partial edit of an idea; a `None` field leaves that column unchanged. */
export type IdeaPatch = {
	title: string | null,
	kind: string | null,
	notes: string | null,
};

/**
 *  Broadcast after any idea row is created or mutated (create, update, discard,
 *  promote); the backlog surface refetches its list.
 */
export type IdeasChanged = null;

/**
 *  A folder whose `project.json` failed to read or validate. Surfaced in the
 *  reconcile report so the UI can badge it; its DB row is left untouched.
 */
export type InvalidManifest = {
	slug: string,
	error: string,
};

/**
 *  A background job row. `status` moves `queued -> running -> (done | failed)`;
 *  no other transition is legal. This repository owns the DB state only; writing
 *  the terminal `events` row is the jobs runtime's job (a later slice).
 */
export type Job = {
	id: string,
	kind: string,
	label: string,
	status: string,
	progress: number,
	payload_json: string | null,
	error: string | null,
	started_at: string | null,
	finished_at: string | null,
};

/**  One progress tick for a job, streamed to `subscribe_job_progress` channels. */
export type JobProgress = {
	job_id: string,
	/**  0.0..=1.0 */
	progress: number,
	message: string | null,
};

/**  Broadcast whenever any `jobs` row is created or changes state. */
export type JobsChanged = null;

/**
 *  The credentials katto stores. Wire values are the snake_case names the
 *  frontend sends.
 */
export type KeyService = "elevenlabs" | "anthropic";

/**  Which credentials exist in the keychain — presence only, never values. */
export type KeysPresent = {
	elevenlabs: boolean,
	anthropic: boolean,
};

/**
 *  A project row. The folder on disk is the source of truth; this row is an index
 *  reconciled on launch. `last_touched_at` records the most recent interaction and
 *  drives the tray's current-project line.
 */
export type Project = {
	slug: string,
	title: string,
	root_path: string,
	status: string,
	target_nle: string,
	shoot_date: string | null,
	publish_date: string | null,
	created_at: string,
	last_touched_at: string | null,
};

/**
 *  A project row plus the on-disk facts the detail surface needs: whether its
 *  `project.json` still validates (`manifest_error` = `Some` message when not —
 *  folders are truth, so a bad manifest badges the project rather than dropping
 *  it) and per-subfolder freshness.
 */
export type ProjectDetail = {
	project: Project,
	manifest_error: string | null,
	freshness: FolderFreshness[],
};

/**
 *  Broadcast after any project row is created or mutated (status, dates,
 *  reconcile add/remove); planner and projects surfaces refetch their lists.
 */
export type ProjectsChanged = null;

/**  The slug of the project an idea was promoted into. */
export type PromoteResult = {
	slug: string,
};

/**
 *  The outcome of a reconcile pass: which rows were added (new valid folders),
 *  which were removed (folders that vanished), and which folders carried an
 *  invalid manifest (left in place).
 */
export type ReconcileReport = {
	added: string[],
	removed: string[],
	invalid_manifests: InvalidManifest[],
};

/**
 *  What onboarding/Settings show after the user picks a studio-root candidate.
 *  Everything except `writable` is advisory — any directory is allowed; katto
 *  warns and lets the owner proceed.
 */
export type RootCheck = {
	path: string,
	writable: boolean,
	on_boot_volume: boolean,
	/**  Whole gigabytes free, `None` if the filesystem query failed. */
	free_gb: number | null,
	low_free_space: boolean,
};

/**
 *  A SQLite `INTEGER PRIMARY KEY` / rowid. Serializes transparently as its inner
 *  integer (the wire value); exported to TypeScript as `number` because these
 *  ids are AUTOINCREMENT rowids that never approach 2^53, and Tauri's JSON IPC
 *  transmits `i64` as a JS number anyway.
 */
export type RowId = number;

/**
 *  Broadcast after any schedule entry is upserted or deleted; the calendar
 *  refetches and the tray's next-shoot line refreshes.
 */
export type ScheduleChanged = null;

/**
 *  A planner schedule entry pinning a project to a date. `kind` is `shoot` or
 *  `publish`. There is at most one entry per `(project_slug, kind)` pair — see
 *  [`upsert`].
 */
export type ScheduleEntry = {
	id: number,
	project_slug: string,
	kind: string,
	date: string,
	note: string | null,
};

/**
 *  The app's settings as the frontend sees them, assembled from the key/value
 *  `settings` table. `default_nle` stays `None` until the first export seeds it
 *  (Phase 5).
 */
export type Settings = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number,
	onboarding_complete: boolean,
	claude_path: string | null,
	keys_present: KeysPresent,
};

/**  Partial update — only the `Some` fields are written. */
export type SettingsPatch = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number | null,
	onboarding_complete: boolean | null,
	claude_path: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

