// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, Error>(__TAURI_INVOKE("get_settings")),
	setSettings: (patch: SettingsPatch) => typedError<Settings, Error>(__TAURI_INVOKE("set_settings", { patch })),
	/**  Most-recent-first page of activity-log events. `before_id` pages backward. */
	listEvents: (limit: number, beforeId: number | null) => typedError<Event[], Error>(__TAURI_INVOKE("list_events", { limit, beforeId })),
	/**  List jobs newest-first. When `active_only`, restrict to `queued`/`running`. */
	listJobs: (activeOnly: boolean) => typedError<Job[], Error>(__TAURI_INVOKE("list_jobs", { activeOnly })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>i) } : v) as typeof v)),
	/**
	 *  Open the native folder picker and inspect the chosen directory. `None` when
	 *  the user cancels. Nothing is persisted here — the wizard saves the path via
	 *  `set_settings` when the step is confirmed.
	 */
	pickStudioRoot: () => typedError<{
	path: string,
	writable: boolean,
	on_boot_volume: boolean,
	/**  Whole gigabytes free, `None` if the filesystem query failed. */
	free_gb: number | null,
	low_free_space: boolean,
} | null, Error>(__TAURI_INVOKE("pick_studio_root")),
	/**
	 *  Store a credential in the macOS keychain. The value is write-only: never
	 *  echoed back, never logged. Presence is recorded in the activity log by
	 *  service name only.
	 */
	storeKey: (service: KeyService, value: string) => typedError<null, Error>(__TAURI_INVOKE("store_key", { service, value })),
	/**  Whether a credential exists for `service`, without exposing its value. */
	keyPresent: (service: KeyService) => typedError<boolean, Error>(__TAURI_INVOKE("key_present", { service })),
	/**
	 *  `which claude` through a login shell, so the owner's PATH additions apply.
	 *  A found path is cached in settings for later phases; not-found is a normal
	 *  outcome, not an error.
	 */
	detectClaude: () => typedError<string | null, Error>(__TAURI_INVOKE("detect_claude")),
	/**
	 *  Finish the wizard: a saved studio root is the one hard requirement; keys
	 *  stay optional (Phase 1 runs no AI).
	 */
	completeOnboarding: () => typedError<null, Error>(__TAURI_INVOKE("complete_onboarding")),
	/**
	 *  Enable or disable launch-at-login, recording the change in the activity
	 *  log. The AppleScript-backed call can block, so it runs off the runtime.
	 */
	setAutostart: (enabled: boolean) => typedError<null, Error>(__TAURI_INVOKE("set_autostart", { enabled })),
	/**  Whether launch-at-login is currently enabled at the OS level. */
	getAutostart: () => typedError<boolean, Error>(__TAURI_INVOKE("get_autostart")),
	/**
	 *  Close the main window: the WebView is destroyed and katto stays resident
	 *  in the tray (same path as clicking the window's close button).
	 */
	sleepToTray: () => typedError<null, Error>(__TAURI_INVOKE("sleep_to_tray")),
	/**  Exit katto completely (same exit path as the tray's Quit item). */
	quitApp: () => typedError<null, Error>(__TAURI_INVOKE("quit_app")),
};

/* Types */
/**
 *  The application error type crossing every command boundary.
 * 
 *  Each variant carries a pre-formatted message string, and serde derives the
 *  tagged `{ kind, message }` wire shape (`kind` = snake_case variant name). The
 *  frontend switches on the stable `kind` slug. `specta::Type` (added alongside
 *  the command layer) types the same shape for the generated bindings, keeping
 *  Rust and TypeScript in lockstep without a hand-written impl.
 */
export type Error = { kind: "db"; message: string } | { kind: "migration"; message: string } | { kind: "job_transition"; message: string } | { kind: "io"; message: string } | { kind: "db_closed"; message: string } | { kind: "keychain"; message: string } | { kind: "onboarding"; message: string } | { kind: "autostart"; message: string };

/**  A row in the append-only activity log. */
export type Event = {
	id: RowId,
	ts: string,
	kind: string,
	project_slug: string | null,
	payload_json: string | null,
};

/**
 *  A background job row. `status` moves `queued -> running -> (done | failed)`;
 *  no other transition is legal. This repository owns the DB state only; writing
 *  the terminal `events` row is the jobs runtime's job (a later slice).
 */
export type Job = {
	id: string,
	kind: string,
	label: string,
	status: string,
	progress: number,
	payload_json: string | null,
	error: string | null,
	started_at: string | null,
	finished_at: string | null,
};

/**
 *  The credentials katto stores. Wire values are the snake_case names the
 *  frontend sends.
 */
export type KeyService = "elevenlabs" | "anthropic";

/**  Which credentials exist in the keychain — presence only, never values. */
export type KeysPresent = {
	elevenlabs: boolean,
	anthropic: boolean,
};

/**
 *  What onboarding/Settings show after the user picks a studio-root candidate.
 *  Everything except `writable` is advisory — any directory is allowed; katto
 *  warns and lets the owner proceed.
 */
export type RootCheck = {
	path: string,
	writable: boolean,
	on_boot_volume: boolean,
	/**  Whole gigabytes free, `None` if the filesystem query failed. */
	free_gb: number | null,
	low_free_space: boolean,
};

/**
 *  A SQLite `INTEGER PRIMARY KEY` / rowid. Serializes transparently as its inner
 *  integer (the wire value); exported to TypeScript as `number` because these
 *  ids are AUTOINCREMENT rowids that never approach 2^53, and Tauri's JSON IPC
 *  transmits `i64` as a JS number anyway.
 */
export type RowId = number;

/**
 *  The app's settings as the frontend sees them, assembled from the key/value
 *  `settings` table. `default_nle` stays `None` until the first export seeds it
 *  (Phase 5).
 */
export type Settings = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number,
	onboarding_complete: boolean,
	claude_path: string | null,
	keys_present: KeysPresent,
};

/**  Partial update — only the `Some` fields are written. */
export type SettingsPatch = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number | null,
	onboarding_complete: boolean | null,
	claude_path: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

