// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, Error>(__TAURI_INVOKE("get_settings")),
	setSettings: (patch: SettingsPatch) => typedError<Settings, Error>(__TAURI_INVOKE("set_settings", { patch })),
	/**  Most-recent-first page of activity-log events. `before_id` pages backward. */
	listEvents: (limit: number, beforeId: number | null) => typedError<Event[], Error>(__TAURI_INVOKE("list_events", { limit, beforeId })),
	/**  List jobs newest-first. When `active_only`, restrict to `queued`/`running`. */
	listJobs: (activeOnly: boolean) => typedError<Job[], Error>(__TAURI_INVOKE("list_jobs", { activeOnly })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>i) } : v) as typeof v)),
};

/* Types */
/**
 *  The application error type crossing every command boundary.
 * 
 *  Each variant carries a pre-formatted message string, and serde derives the
 *  tagged `{ kind, message }` wire shape (`kind` = snake_case variant name). The
 *  frontend switches on the stable `kind` slug. `specta::Type` (added alongside
 *  the command layer) types the same shape for the generated bindings, keeping
 *  Rust and TypeScript in lockstep without a hand-written impl.
 */
export type Error = { kind: "db"; message: string } | { kind: "migration"; message: string } | { kind: "job_transition"; message: string } | { kind: "io"; message: string } | { kind: "db_closed"; message: string } | { kind: "keychain"; message: string };

/**  A row in the append-only activity log. */
export type Event = {
	id: RowId,
	ts: string,
	kind: string,
	project_slug: string | null,
	payload_json: string | null,
};

/**
 *  A background job row. `status` moves `queued -> running -> (done | failed)`;
 *  no other transition is legal. This repository owns the DB state only; writing
 *  the terminal `events` row is the jobs runtime's job (a later slice).
 */
export type Job = {
	id: string,
	kind: string,
	label: string,
	status: string,
	progress: number,
	payload_json: string | null,
	error: string | null,
	started_at: string | null,
	finished_at: string | null,
};

/**  Which credentials exist in the keychain — presence only, never values. */
export type KeysPresent = {
	elevenlabs: boolean,
	anthropic: boolean,
};

/**
 *  A SQLite `INTEGER PRIMARY KEY` / rowid. Serializes transparently as its inner
 *  integer (the wire value); exported to TypeScript as `number` because these
 *  ids are AUTOINCREMENT rowids that never approach 2^53, and Tauri's JSON IPC
 *  transmits `i64` as a JS number anyway.
 */
export type RowId = number;

/**
 *  The app's settings as the frontend sees them, assembled from the key/value
 *  `settings` table. `default_nle` stays `None` until the first export seeds it
 *  (Phase 5).
 */
export type Settings = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number,
	onboarding_complete: boolean,
	claude_path: string | null,
	keys_present: KeysPresent,
};

/**  Partial update — only the `Some` fields are written. */
export type SettingsPatch = {
	studio_root: string | null,
	default_nle: string | null,
	idle_reap_minutes: number | null,
	onboarding_complete: boolean | null,
	claude_path: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

