#!/usr/bin/env python3
"""Extract thumbnail variant titles from every contact-sheet.html in a video folder.

Each `videos/<slug>-<date>/thumbnails/<round>/contact-sheet.html` produced by
the thumbnail-and-title-generator skill contains three variants (A, B, C). For each we want:

- The thumbnail overlay text       — `<span class="variant-text">…</span>`
- The YouTube title                — `<span class="variant-yt-text">…</span>`

This script walks every round (including `-vertical` rounds), parses each
contact sheet, and emits a single JSON document on stdout:

    [
      {
        "round": "round-1",
        "path": "thumbnails/round-1/contact-sheet.html",
        "variants": [
          {"letter": "A", "overlay": "…", "yt_title": "…"},
          {"letter": "B", "overlay": "…", "yt_title": "…"},
          {"letter": "C", "overlay": "…", "yt_title": "…"}
        ]
      },
      …
    ]

The first three matches per file are taken; the `<title>`/`<h1>` at the top
of the contact sheet (which is just round metadata) is ignored.

Why regex instead of an HTML parser? The contact sheets are generated by
the thumbnail-and-title-generator skill from a known template — the markup is stable
and a parser dependency would be overkill.

Usage:
    python3 extract_titles.py <video-folder>
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

OVERLAY_RX = re.compile(
    r'<span\s+class="variant-text">(?P<text>.*?)</span>',
    re.DOTALL,
)
YT_TITLE_RX = re.compile(
    r'<span\s+class="variant-yt-text">(?P<text>.*?)</span>',
    re.DOTALL,
)
LETTER_RX = re.compile(
    r'<span\s+class="variant-letter">(?P<text>.*?)</span>',
    re.DOTALL,
)


def clean(s: str) -> str:
    """Strip nested tags, decode entities, collapse whitespace."""
    s = re.sub(r"<[^>]+>", "", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def parse_contact_sheet(path: Path) -> list[dict[str, str]]:
    """Return a list of {letter, overlay, yt_title} for the first 3 variants."""
    text = path.read_text(encoding="utf-8")
    letters = [clean(m.group("text")) for m in LETTER_RX.finditer(text)]
    overlays = [clean(m.group("text")) for m in OVERLAY_RX.finditer(text)]
    yt_titles = [clean(m.group("text")) for m in YT_TITLE_RX.finditer(text)]

    # Some contact sheets repeat the variant block lower down as a template
    # reference. The authoritative copies are the first three of each.
    letters = letters[:3]
    overlays = overlays[:3]
    yt_titles = yt_titles[:3]

    n = min(len(overlays), len(yt_titles))
    if n == 0:
        return []
    # Pad letters in case they're missing — A, B, C fallback.
    while len(letters) < n:
        letters.append(chr(ord("A") + len(letters)))

    return [
        {"letter": letters[i], "overlay": overlays[i], "yt_title": yt_titles[i]}
        for i in range(n)
    ]


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Extract thumbnail variant titles from a video folder"
    )
    ap.add_argument(
        "video_folder",
        type=Path,
        help="Path to videos/<slug>-<date>/",
    )
    ap.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print the JSON output",
    )
    args = ap.parse_args()

    thumbs_dir = args.video_folder / "thumbnails"
    if not thumbs_dir.is_dir():
        print(f"error: no thumbnails/ directory at {thumbs_dir}", file=sys.stderr)
        return 1

    rounds: list[dict] = []
    # Sort by name so output is stable across runs.
    for round_dir in sorted(thumbs_dir.iterdir()):
        if not round_dir.is_dir():
            continue
        sheet = round_dir / "contact-sheet.html"
        if not sheet.exists():
            continue
        variants = parse_contact_sheet(sheet)
        if not variants:
            print(
                f"warn: no variants found in {sheet}",
                file=sys.stderr,
            )
            continue
        rounds.append(
            {
                "round": round_dir.name,
                "path": str(sheet.relative_to(args.video_folder)),
                "variants": variants,
            }
        )

    if not rounds:
        print("error: no contact sheets with variants found", file=sys.stderr)
        return 1

    indent = 2 if args.pretty else None
    print(json.dumps(rounds, indent=indent, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
